### ISSUE TITLE
settle command

### ISSUE THREAD

**Issue by nochinator** [Syclusion/Archimedes-Fluids-SUPERPERFORMANT#1]
could we get a command that settles liquids quickly? maybe it could allow setting the tick speed of liquids. Not sure how are it would be to do, but adding a function to the end of world gen that settles all the liquids would also be a really good feature to add.

**Comment by Syclusion** [comment]
So processing double updates for one block in a single tick is kind of out of the question. That doubles overhead from a mod that already uses most of the resources to tick when enough updates occur. Keep in mind a tick is 1/20th of a second at normal speed, I am working on an even better version with a TON of features and changes but double updates just simply isn't feasible

**Comment by Syclusion** [comment]
I will however look into commands, for setting the updates per tick limit. Currently my indev uses a config file, but that is a possibility

**Comment by nochinator** [comment]
ok cool, thanks.

**Comment by Syclusion** [comment]
Yup, the new update is in testing if you would like to try it. And I should have explained this a little better, but the updates are directly tied to tick speed. So in a perfect world, the blocks would update 20 times in a second. Obv this mod has a lot of calculations that make that pretty hard to maintain, so the average speed takes a nosedive and so do the amount of "visual" updates. The newest version helps a lot with that by increasing performance a ton, but still has a ways to go.
